language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
- 2.7.10
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  api_key:
    secure: FZSWM4krVbMne6z6fjol0hptSqCZo3IriODSSEYaC8vY7cYWPNm4M7B0wN/c2I0i/iFkMGkVZzsmD4yo1NA8OHhPLQN8/0iYyN1CcVcbWifsAqnTIlMpQOrkDr7elrXZtcdxDda2kimpHswqFPHykqQ5N4Yvf4hzDzbybTyhyws99JDtRll8Ewt05/Va/zuHDgqVJD7mPjPoa8gaPJkFuhAtYTuM0/Iv2YWWBlWO9Tnc582/BcxcJ3b4U0maJP3noGZjQTEI8ecwN2TFJPTRwuY5/ctiQFhVsOodrtfNd6iNBO6TcngUw0w78TA+tNottHxqG2mSw8/OwqSCxZ/1RjqypwfwmDStIAlu07ED9IH9SeDoVrTSfKr0Gqlh8q/lFAec3Qm2+9wejuuBUhFL8GZS50SykSxo5JMBTlRsqzuBD3ph1hBLodCMzkLwQPxD9GvV6NjlW+VN1XIu/KnDkh+QrcJt0YDIz4O8bH4U2PhNO+orgYMRV1g5744+VWX+yOm3/flU+NOmgNA+uUvWzb2IADF5hSD8rcLSxRqp0FoQ1oGxiH/yOflkv+nMJjWWcxfBcFS8lt5JPSF6E2lj1pEt/nLMJ9L8cJH2hISjiYRVgRlP0eL4ewE4900D5tmSxnadMeJqanFHnuOJ0OQGrU4iy0dD58YMSsGhDErfBRo=
  file: size.png
  on:
    repo: britzl/dmengine_size
