language: python
env:
  global:
    - GITHUB_REPO: "britzl/dmengine_size"
    - secure: "DEBHvnwmc6vOE2L4vs+LvcLfKRoXgzX2ylb5lv35sL2/KONfSsVG3YgCh0yY42O0K98fCnApwecYvbptKcIwW8HettUw4JYhhdlZHQU/sryoXkHQ/XDfngZmX2Wqjpl2BZxrLDoVARp9cuYONwWjEyGw8pHBRtSdq2lUsTFznSGl8lOEdi2tRAi7IgTKeF1Fc6tWu2492AI1Mh+K1ixI21P+FEofjcfVZAYZGFBiOeN/z2i9oZM19hVLr+QdiAjDOLlDGcQ3BolUuUanKxqGFbQjKVf4HaBDwh42JTzRuRfoSg3Ue9Mo7yU5qajuwQcgmk+GbQIll51lj2dYia8IGtNaSVUcuGQxsCi4G0xWctTErariWRs86ETzLiMqU57kMteQ85578vQsSwMzuUWuJ7xS3hRf9QPwV4e74Q3hWuO2pJI36GVR5QJ/7Oh/2v7e9Rj5c1pLWuUKKM3mvAhs9Zwyo51j1siUNVjDrqBUjbV0sneDAOCnRHZ7/2u85cAlNjgeRVTuiwfNr65aEluNx1dZeg/AdAfXDiIaD385DFsLzmpKzjvG6My08Y3BW/cmRL3Cmv74ZDlApx1MRQ8ppvYGep/B5RMhENENX/dNNa71WX4E6qpTkZqu3Nnxj7ws/Sw6vBfCdEfcGEemyu5xXnPBWPU3xtIxnLaTeg6RetI="
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
- 2.7.10
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
