language: python
env:
  global:
    - secure: "iPLunTQopNY/5lq19spOSz8skudzAiEntoZosf+Y3h39wz+KnDWlfJo8XpTuD1Yl9WGjpma30djE9k6GgSIbGhRvpH+h/KSNdqkNpFuyXwCTT1bJYlpNTOWrUb58KwwqroSVQeKQ1yCEVNrOHbCxpLSjcPeS9OscR6/v7TtITV50MpbVwgF0mL8jaKUnpq9IUB6S6PVyqxZbqwyNanz7ehxc6Kg4VJ7oo53yT/7dC5onUgUkP0sy3Fxpq2qp4o+J0+U1p0o7xrwwgcoD2pwZMJXesZBhX2BiEWMAcVMiJQOGiVjbmfzFotlf6mewa2NEl+4t/znr+wU19AKb+hpEFbRyBho9YpY3k1yxeB4giyUeTu+AthttPkk52M7pJuTv3HD5XQqtSAtbbPAtdNQv6/9MjyMFPEyGxEwxob9IxOnH3YhDKr3+eNRqo5dxoMMUsg/BgSbdSSoD7NquPpe719fboWuVyNomkUEkXfecOMqwnD9PiBfEPhymsAwEjQySKjRbLgDpxfozbkquF0ONegIV4FVjOHmQf0sfurFz9mlyMYlbo2wpOMtEdLb0gM4bHVyrmUYlOu/T1gjCoe9Ah2u3D3dSy5Ti05QgTx1wiftNSJWRDBr7eRvQCOe9i3JbMmH1RWuWnUH/WJ7ByhjGgUlwBdrOtnHvGrHGxSgYCgE="
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
- 2.7.10
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
after_success:
- "./.travis/deploy.sh"
